# Generated by Django 4.2.16 on 2026-05-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TravelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="景点名称")),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所在区域"
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="城市")),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="评分"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="标签"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="图片链接"
                    ),
                ),
                (
                    "hot_score",
                    models.FloatField(blank=True, null=True, verbose_name="热度评分"),
                ),
                (
                    "comment_count",
                    models.IntegerField(blank=True, null=True, verbose_name="评论数量"),
                ),
                (
                    "price",
                    models.FloatField(blank=True, null=True, verbose_name="票价"),
                ),
            ],
            options={
                "verbose_name": "景点信息",
                "verbose_name_plural": "景点信息",
                "db_table": "travel_travelinfo",
            },
        ),
    ]
